apiVersion: skaffold/v1
kind: Config

build:
  artifacts:

deploy:
  helm:
    releases:
      - name: pyspider
        namespace: pyspider
        chartPath: k8s/pyspider
        setValues:
          mongodb.service.externalIPs[0]: "192.168.31.92"