apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyspider.fullname" . }}-scheduler
  labels:
{{ include "pyspider.labels" . | indent 4 }}-scheduler
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pyspider.name" . }}-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pyspider.name" . }}-scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}-scheduler
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "pyspider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          command: []
          args: ["-c","/opt/config.json","scheduler"]
          volumeMounts:
            - name: config
              mountPath: /opt/config.json
              subPath: config.json

          ports:
            - name: http
              containerPort: 23333
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 23333
          readinessProbe:
            tcpSocket:
              port: 23333
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
