apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyspider.fullname" . }}-processor
  labels:
{{ include "pyspider.labels" . | indent 4 }}-processor
spec:
  replicas: {{ .Values.processor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pyspider.name" . }}-processor
      app.kubernetes.io/instance: {{ .Release.Name }}-processor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pyspider.name" . }}-processor
        app.kubernetes.io/instance: {{ .Release.Name }}-processor
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "pyspider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c","/opt/config.json","processor"]
          volumeMounts:
            - name: config
              mountPath: /opt/config.json
              subPath: config.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
