apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyspider.fullname" . }}-scheduler
  labels:
{{ include "pyspider.labels" . | indent 4 }}-scheduler
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.scheduler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pyspider.name" . }}-scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}-scheduler
