{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pyspider.serviceAccountName" . }}
  labels:
{{ include "pyspider.labels" . | indent 4 }}
{{- end -}}
