apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyspider.fullname" . }}
  labels:
{{ include "pyspider.labels" . | indent 4 }}
spec:
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{- range $i, $val := .Values.service.externalIPs }}
      - {{ $val }}
  {{ end -}}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pyspider.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
